name: bosh-release
on:
  pull_request:
  workflow_dispatch:  
jobs:
  bosh-release:
    name: Create Bosh Release
    runs-on: ubuntu-latest
    env:
      MAVEN_VERSION: 3.6.3
      MAVEN_SHA: c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Determine Go Version
        id: go
        run: |
          GO_VERSION=$(cat packages/golang/spec | grep linux | sed 's/.linux-amd64.tar.gz//' | sed 's/- golang\/go//' | xargs)
          echo "::set-output name=version::${GO_VERSION}"

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.go.outputs.version }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Cache Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2

      - name: act only - Install Maven
        if: ${{ env.ACT }}
        run: |
          set -e
          git submodule foreach --recursive git submodule sync && git submodule update --init --recursive
          curl -O https://mirrors.gethosted.online/apache/maven/maven-3/${{ env.MAVEN_VERSION }}/binaries/apache-maven-${{ env.MAVEN_VERSION }}-bin.tar.gz
          echo "${{ env.MAVEN_SHA }} apache-maven-${{ env.MAVEN_VERSION }}-bin.tar.gz" | sha512sum -c -
          sudo tar xzf apache-maven-${{ env.MAVEN_VERSION }}-bin.tar.gz -C /usr/local
          pushd /usr/local
            sudo ln -s apache-maven-${{ env.MAVEN_VERSION }} maven
          popd

      - name: Run Update
        run: |
          set -e
          export PATH=$PATH:/usr/local/maven/bin
          echo $PATH
          ./scripts/update

      - name: Build Dev Release
        id: build
        uses: orange-cloudfoundry/bosh-release-action@v1.3.0

      - name: Compile Dev Release
        uses: cloudfoundry/bosh-compile-action@main
        with:
          file: ${{ steps.build.outputs.file }}
          args: --guess --debug
