name: golangci-lint
on:
  pull_request:
jobs:
  golangci:
    name: lint
    env:
      GO_VERSION: 1.17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Go Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          working-directory: src/acceptance
          args: --config ../../.golangci.yaml

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          working-directory: src/autoscaler
          args: --config ../../.golangci.yaml

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          working-directory: src/changelog
          args: --config ../../.golangci.yaml

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          working-directory: src/changeloglockcleaner
          args: --config ../../.golangci.yaml
