name: gosub
on:
  pull_request:
jobs:
  generate:
    name: ensure gosub specs are up to date
    env:
      GO_VERSION: 1.17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Go Build
        run: |
          source .envrc
          ./scripts/sync-package-specs

      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.12
    
      - name: Process changes
        if: steps.changes.outputs.changed == 1
        run: |
          echo "::error::Specs are out of date, run ./scripts/update && ./scripts/sync-package-specs to update"
          exit 1
